layout_spectrum: 0.9807379541452974
typography_spectrum: 0.5439915051683784
color:
  brandStrength: 0.42915309383533895
  lightness: 0.5111168583389372
  saturation: 0.40248418669216335
  rhythmicContrast: 0.87447180878371
  brandColors:
    - '#9B8442'
    - '#FEEC01'
    - '#2B2029'
    - '#554843'
    - '#7E6E4F'
content_rating:
  adult: false
opengraph:
  type: Coyote Ridge Survival Supplies
  appId: 'https://www.facebook.com/CoyoteRidgeSurvival/#'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/a5c66e97-c2c1-4590-93c0-9cc20193708b.jpg
author:
  name: Greg Griffith
  email: ggriffith@coyoteridgesurvival.com
  url: www.coyoteridgesurvival.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf0c17c7-0b1f-4afb-982d-a50f6c611b4d.png
name: Coyote Ridge Survival Supplies
title: 'Expect the worst, hope for the best, prepare for anything.'
