typography_spectrum: 0.2967098120134324
color:
  brandStrength: 0.6686358484439552
  lightness: 0.3881754220928997
  saturation: 0.8590257507748902
  rhythmicContrast: 0.31036537629552186
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.14050932019017637
author:
  name: Greg Griffith
  email: ggriffith@coyoteridgesurvival.com
  url: www.coyoteridgesurvival.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf0c17c7-0b1f-4afb-982d-a50f6c611b4d.png
name: Coyote Ridge Survival Supplies
