name: Coyote Ridge Survival Supplies
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf0c17c7-0b1f-4afb-982d-a50f6c611b4d.png
layout_spectrum: 0.9807379541452974
typography_spectrum: 0.5439915051683784
opengraph:
  type: Coyote Ridge Survival Supplies
  appId: '@CoyoteRidgeSurvival'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/a5c66e97-c2c1-4590-93c0-9cc20193708b.jpg
color:
  brandColors:
    - '#9B8442'
    - '#FEEC01'
    - '#2B2029'
    - '#554843'
    - '#7E6E4F'
  brandStrength: 0.42915309383533895
  lightness: 0.5111168583389372
  saturation: 0.40248418669216335
  rhythmicContrast: 0.87447180878371
title: 'Expect the worst, hope for the best, prepare for anything.'
author:
  name: Greg Griffith
  url: www.coyoteridgesurvival.com
  email: ggriffith@coyoteridgesurvival.com
content_rating:
  adult: false
navigation:
  - name: About Us
    id: 2b407485-1bd6-4322-8d2b-eb03e6887a50
    type: content
